services:

  mysql:
    image: mysql:8
    container_name: mysql-pcstore
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcstore
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pcstore_backend_dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: pcstore
      JWT_SECRET: un_secret_tres_long_et_aleatoire_ici_2024!
      PORT: 3001
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend/pc-configurator
      dockerfile: Dockerfile.dev
    container_name: pcstore_frontend_dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend/pc-configurator:/app
      - /app/node_modules